import { Orbitron, Share_Tech_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const orbitron = Orbitron({ subsets: ["latin"], variable: '--font-orbitron' });
const shareTechMono = Share_Tech_Mono({ weight: '400', subsets: ["latin"], variable: '--font-share' });
const jetBrainsMono = JetBrains_Mono({ subsets: ["latin"], variable: '--font-mono' });

export const metadata = {
  title: "Dishant's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${orbitron.variable} ${shareTechMono.variable} ${jetBrainsMono.variable}`}>
      <body className={`${jetBrainsMono.className} scanlines bg-background text-foreground min-h-screen max-w-full overflow-x-hidden`}>
        {children}
      </body>
    </html>
  );
}
